### PR TITLE
PDINSTANCE=1 fix (untested)

### PR DESCRIPTION
**Pull request by njazz**

### CODE REVIEW

**Comment by njazz** [comment]
also needs fix in eclass.cpp
eclass_attr_redirect(t_eclass* c, const char* attrname, t_gotfn fn)

**Comment by njazz** [comment]
in ceammc_property_info.h
bool addEnums(std::initializer_list<t_symbol*> s_list) CEAMMC_WARN_UNUSED;
s_list is defined as macro when PDINSTANCE==1

**Comment by njazz** [comment]
also in ceammc_pd.cpp

currentListOfExternals()
pd::External::methods()

**Comment by njazz** [comment]
more changes to eclass.cpp:

#define GSYM(name) currently creates constant symbols that don't work in PDINSTANCE=1

**Comment by uliss** [comment]
rewritten with ceammc::class_method_name() method, taking into account both PDINSTANCE and Pd version (in 0.52 changes underlying struct size)

```C
template <typename T>
T* class_get_method(t_class* c, int n)
{
#ifdef PDINSTANCE
    return reinterpret_cast<T*>(c->c_methods[pd_this->pd_instanceno]) + n;
#else
    return reinterpret_cast<T*>(c->c_methods) + n;
#endif
}

template <typename T>
t_symbol* class_get_method_name(t_class* c, int n)
{
    return class_get_method<T>(c, n)->me_name;
}
```

**Pull request closed without merging**
